spring:
  application:
    name: notification-service # Change the application name to order-service

server:
  port:
    7004


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/