spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=0
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/products/**
              filters:
                - StripPrefix=0
            - id: category-service
              uri: lb://product-service
              predicates:
                - Path=/categories/**
              filters:
                - StripPrefix=0
            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/cart/**
              filters:
                - StripPrefix=0
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
              filters:
                - StripPrefix=0
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payments/**
              filters:
                - StripPrefix=0
            - id: shipping-service
              uri: lb://shipping-service
              predicates:
                - Path=/shipments/**
              filters:
                - StripPrefix=0
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**
              filters:
                - StripPrefix=0
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                allowedHeaders:
                  - "*"
                allowCredentials: true

server:
  port: 7000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true



jwt:
  secret: wassim-lagnaoui-ecommerce-secret-key-32-char
  expiration: 86400000