spring:
  application:
    name: order-service # Change the application name to order-service

server:
  port:
    8086 # Change the port number to 8086


eureka:
    client:
        service-url:
          defaultZone: http://localhost:8761/eureka/