spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=cart_db
    username: appuser
    password: apppassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  web:
    client:
      connect-timeout: 5000 # Connection timeout in milliseconds
      read-timeout: 5000 # Read timeout in milliseconds
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: cart-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

#RestClient Timeoutconfiguration


server:
  port: 7003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


# Actuator endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakerevents,retryevents,beans,env,metrics, circuitbreakers, timelimiters

# Services URLs :
services:
  product-service:
    url: http://PRODUCT-SERVICE
  payment-service:
    url: http://PAYMENT-SERVICE
  user-service:
    url: http://USER-SERVICE
  order-service:
    url: http://ORDER-SERVICE
  cart-service:
    url: http://CART-SERVICE
  shipping-service:
    url: http://SHIPPING-SERVICE


resilience4j:
  circuitbreaker:
    instances:
        productServiceCircuitBreaker:
            registerHealthIndicator: true
            sliding-window-type: time_based  # Use time-based sliding window to calculate failure rate over a specific time period
            sliding-window-size: 10 # Time window size in seconds for calculating failure rate
            failureRateThreshold: 50 # Percentage of failed calls to open the circuit
            waitDurationInOpenState: 10000 # Time to wait before transitioning from open to half-open state (in milliseconds)
            permittedNumberOfCallsInHalfOpenState: 3 # Number of calls allowed in half-open state before deciding to close or open the circuit
            minimumNumberOfCalls: 5 # Minimum number of calls required before calculating the failure rate
            ignore-exceptions:
              - com.wassimlagnaoui.ecommerce.Cart_Service.Exception.ProductNotFoundException
        orderServiceCircuitBreaker:
            registerHealthIndicator: true
            sliding-window-type: time_based
            sliding-window-size: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 10000
            permittedNumberOfCallsInHalfOpenState: 3
            minimumNumberOfCalls: 2
  retry:
    instances:
        productServiceRetry:
            max-attempts: 3
            wait-duration: 2000 # Time to wait between retry attempts (in milliseconds)
        orderServiceRetry:
            max-attempts: 3
            wait-duration: 2000


